version: '3.9'

services:
  db:
    image: postgres:16
    container_name: winxi-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: winxi-server.Dockerfile
    container_name: winxi-api
    restart: unless-stopped
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db

  client:
    build:
      context: ./winxi-client
    container_name: winxi-client
    restart: unless-stopped
    ports:
      - 5173:5173
    depends_on:
      - api

volumes:
  postgres_data: